title:              Marco's bughome
email:              marco_hmc@163.com
description:        Knowledge is for sharing!
author:             Marco Huang
baseurl:            ""
url:                "https://marco_hmc.github.io"

# Social Profiles
# twitter_username:   wait
github_username:    marco-hmc
# facebook_username:  wait
# instagram_username:  
linkedin_username: 茂春-黄-02bb571a6

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
